apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-single
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  fsType: "ext4"
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
  fromBackup: ""

