apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-s3gw-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single
  resources:
    requests:
      storage: 2Gi

