---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Chart.Name }}-secret'
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  RGW_DEFAULT_USER_ACCESS_KEY: {{ .Values.default.access_key | quote }}
  RGW_DEFAULT_USER_SECRET_KEY: {{ .Values.default.secret_key | quote }}
