---
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Chart.Name }}-svc'
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.aquarist-labs.io/name: {{ .Chart.Name }}
  ports:
    - name: s3
      protocol: TCP
      port: 80
      targetPort: 7480
