{{ if not .Values.pvc }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-single
  namespace: {{ .Release.Namespace }}
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindMode: Immediate
parameters:
  fsType: ext4
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
  fromBackup: ""
{{ end }}
